repos:
  - repo: https://github.com/psf/black
    rev: 24.8.0        # pin to a specific Black version you want
    hooks:
      - id: black
        language_version: python3   # or "python3" to use your default
